import "./lose_durability_on_dig";
import "./medkit";
import "./morphine_syringe";
import "./painkillers";
import "./scp063";
import "./scp096_picture";
import "./scp207";
import "./scp420j";
import "./scp500";
